// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnZp42elUDYUi--N53dt0htK2U1Z7OZuo',
    appId: '1:140525202489:web:55dacb5243a58998fff1e8',
    messagingSenderId: '140525202489',
    projectId: 'meetu-b04a2',
    authDomain: 'meetu-b04a2.firebaseapp.com',
    storageBucket: 'meetu-b04a2.appspot.com',
    measurementId: 'G-WGTZTV0L2R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlQvvhojhC_0BFi2x_5bTc4iay1xIOzo4',
    appId: '1:140525202489:android:afb8a5f85d2cf7aefff1e8',
    messagingSenderId: '140525202489',
    projectId: 'meetu-b04a2',
    storageBucket: 'meetu-b04a2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwhDmuN3OSy8MWeaPLX0ULvCTpx9s942c',
    appId: '1:140525202489:ios:5bde39a0d9562c17fff1e8',
    messagingSenderId: '140525202489',
    projectId: 'meetu-b04a2',
    storageBucket: 'meetu-b04a2.appspot.com',
    iosClientId: '140525202489-7423e0mrnkrsjj0oacvn6kgpua90r5ut.apps.googleusercontent.com',
    iosBundleId: 'com.example.meetu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwhDmuN3OSy8MWeaPLX0ULvCTpx9s942c',
    appId: '1:140525202489:ios:98b9a62351d39319fff1e8',
    messagingSenderId: '140525202489',
    projectId: 'meetu-b04a2',
    storageBucket: 'meetu-b04a2.appspot.com',
    iosClientId: '140525202489-fmumn148scssf989b2mk6rd1kl5b6vat.apps.googleusercontent.com',
    iosBundleId: 'com.example.meetu.RunnerTests',
  );
}
